app/models/employee.py
from app import db
from app.models.utils import ModelMixin


class Employee(db.Model, ModelMixin):
    __tablename__="employees"

    id = db.Column(db.Integer, primary_key=True)

    name = db.Column(db.String(50), nullable=False)
    position = db.Column(db.String(50), nullable=False)
    phone = db.Column(db.String(16), nullable=True, unique=True)
    email = db.Column(db.String(50), nullable=False, unique=True)
    birthday = db.Column(db.DateTime(), nullable=True)
    company_id = db.Column(db.Integer, db.ForeignKey('companies.id', ondelete='CASCADE'))
    
    def __repr__(self):
        return "<Employee(name='%s', email='%s', phone='%s')>" % (
            self.name,
            self.email,
            self.phone,)

app/forms/employee.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, DateField
from wtforms_sqlalchemy.fields import QuerySelectField
from wtforms.validators import DataRequired, Length, ValidationError
from app.models import Employee, Company


def choice_query():
    return Company.query

class AddEmployeeForm(FlaskForm):
    name = StringField("Employee name", [DataRequired(), Length(1, 50)])
    position = StringField("Position", [DataRequired(), Length(2, 50)])
    phone = StringField("Phone", [Length(9, 16)])
    email = StringField("Email", [DataRequired(), Length(4, 50)])
    birthday = DateField("Birthday")
    company_id = QuerySelectField("Company", query_factory=choice_query, allow_blank=False, get_label='title')
    submit = SubmitField("Create")
    
    def validate_email(form, field):
        if Employee.query.filter_by(email=field.data).first():
            raise ValidationError('This email is taken.')
    
class EmployeeForm(FlaskForm):
    name = StringField("Employee name", [DataRequired(), Length(1, 50)])
    position = StringField("Position", [DataRequired(), Length(2, 50)])
    phone = StringField("Phone", [Length(9, 16)])
    email = StringField("Email", [DataRequired(), Length(4, 50)])
    birthday = DateField("Birthday")
    company_id = QuerySelectField("Company", query_factory=choice_query, allow_blank=False, get_label='title')
    submit = SubmitField("Save")
    

app/views/employee.py
from flask import render_template, Blueprint, flash, request, redirect, url_for
from flask_login import login_required
from app.forms import AddEmployeeForm, EmployeeForm
from app.models import Employee, Company

employee_blueprint = Blueprint("employee", __name__)


@employee_blueprint.route("/employees", methods=["GET"])
@login_required
def employees():
    employees = Employee.query.all()
    return render_template("employee/employees.html", employees=employees)

@employee_blueprint.route("/employee/creation", methods=["GET", "POST"])
@login_required
def employee_creation():
    form = AddEmployeeForm()
    if form.validate_on_submit():
        employee = Employee(
            name=form.name.data,
            position=form.position.data,
            phone=form.phone.data,
            email=form.email.data,
            birthday=form.birthday.data,
            company_id=int(form.company_id.data.id),
        )
        employee.save()
        flash("Employee has been successfully added", "info")
        return redirect(url_for("employee.employees"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    return render_template("employee/employee_creation_profile.html", form=form)

@employee_blueprint.route("/employee/deletion/<int:id>")
@login_required
def employee_deletion(id):
    employee_to_delete: Employee = Employee.query.get(id)
    employee_to_delete.delete()
    return redirect(url_for("employee.employees"))

@employee_blueprint.route("/employee/<int:id>", methods=["GET", "POST"])
@login_required
def employee_profile(id):
    employee: Employee = Employee.query.get(id)
    form = EmployeeForm()
    if form.validate_on_submit():
        employee.name = (form.name.data,)
        employee.position = (form.position.data,)
        employee.phone = (form.phone.data,)
        employee.email = (form.email.data,)
        employee.birthday = (form.birthday.data,)
        employee.company = (form.company_id.data,)
        employee.save()
        flash("Employee successfully updated", "info")
        return redirect(url_for("employee.employees"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    elif request.method == "GET":
        form.name.data = employee.name
        form.position.data = employee.position
        form.phone.data = employee.phone
        form.email.data = employee.email
        form.birthday.data = employee.birthday
        form.company_id.data = Company.query.filter_by(id=employee.company_id).first()
    return render_template("employee/employee_creation_profile.html", employee_id=employee.id, form=form)

@employee_blueprint.route("/company/<int:id>/employees", methods=["GET", "POST"])
@login_required
def company_employees(id):
    company_employees = Employee.query.filter_by(company_id=id)
    company = Company.query.get(id)
    return render_template("employee/employees.html", employees=company_employees, company=company)

app/templates/employee/employee_creation_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
  <div class="card w-50 mx-auto">
    <div class="card-header">
      <h4 class="card-title">Employee{% if not employee_id %} Creation{% endif %}</h4>
    </div>
    <div class="card-body">
      <form class="form" role="form" {% if employee_id %} action="{{ url_for('employee.employee_profile', id=employee_id) }}" {% else %} action="{{ url_for('employee.employee_creation') }}" {% endif %} method="post">
        <div class="form-group">
          {{form.name.label}}
          {{form.name(class='form-control')}}
          {% for error in form.errors.name %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>
        <div class="form-group">
          {{form.position.label}}
          {{form.position(class='form-control')}}
          {% for error in form.errors.position %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>
        <div class="form-group">
            {{form.phone.label}}
            {{form.phone(class='form-control')}}
            {% for error in form.errors.phone %}
              <small class="text-danger">{{error}}</small>
            {% endfor %}
        </div>
        <div class="form-group">
            {{form.email.label}}
            {{form.email(class='form-control')}}
            {% for error in form.errors.email %}
              <small class="text-danger">{{error}}</small>
            {% endfor %}
        </div>
        <div class="form-group">
          {{form.birthday.label}}
          {{form.birthday(class='form-control')}}
          {% for error in form.errors.birthday %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>
        <div class="form-group">
          {{form.company_id.label}}
          {{form.company_id(class='form-control')}}
          {% for error in form.errors.company_id %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>

        {{form.submit(class='btn btn-primary')}}
      </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/employee/employees.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center">{% if company %}{{ company.title }}'s e{% else %}E{% endif %}mployees</h1>
    <hr>
    {% if employees %}
    <div class="row d-flex justify-content-between">
        {% for employee in employees %}
            <div class="card m-3 col-md-5 col-lg-3">
                <div class="card-body">
                    <h4 class="card-title">{{ employee.name }}</h4>
                    <hr>
                    <p class="card-text">{{ employee.position }}</p>
                    <p class="card-text text-muted">{{ employee.email }}</p>
                    <div class="d-flex justify-content-start">
                        <a href="{{ url_for('employee.employee_profile', id=employee.id) }}" class="card-link">Profile</a>
                        <a href="{{ url_for('employee.employee_deletion', id=employee.id) }}" class="card-link">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <p class="text-center pt-100 text-muted">There is no employees yet.</p>
    {% endif %}
    <hr>
    <div class="d-flex flex-column text-center">
        <p class="text-secondary">Want to create a employee? Press the button below.</p>
        <a class="btn btn-primary" href="{{ url_for('employee.employee_creation') }}" role="button">Create Employee</a>
    </div>

</div>
{% endblock %}