app/models/company.py
from app import db
from app.models.utils import ModelMixin


class Company(db.Model, ModelMixin):
    __tablename__ = "companies"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(100), nullable=False)
    location = db.Column(db.String(100), nullable=False)
    
    employees = db.relationship('Employee', backref='companies', passive_deletes='all')
    
    def __repr__(self):
        return "<Company(title='%s', location='%s')>" % (
            self.title,
            self.location,)

app/forms/company.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired, Length, ValidationError
from app.models import Company


class CompanyCreationForm(FlaskForm):
    title = StringField('Title', [DataRequired(), Length(min=4, max=100)])
    location = StringField('Location', [DataRequired(), Length(min=4, max=100)])
    submit = SubmitField("Create")

    def validate_title(form, field):
        if Company.query.filter_by(title=field.data).first():
            raise ValidationError('This title is taken.')


class CompanyForm(FlaskForm):
    title = StringField('Title', [DataRequired(), Length(min=4, max=100)])
    location = StringField('Location', [DataRequired(), Length(min=4, max=100)])
    submit = SubmitField("Save")
    
    def validate_title(form, field):
        if Company.query.filter_by(title=field.data).first():
            raise ValidationError('This title is taken.')

app/views/company.py
from flask import Blueprint, render_template, redirect, flash, url_for, request
from flask_login import login_required

from app.models import Company
from app.forms import CompanyCreationForm, CompanyForm

company_blueprint = Blueprint("company", __name__)


@company_blueprint.route("/companies")
@login_required
def companies():
    companies = Company.query.all()
    return render_template("/company/companies.html", companies=companies)


@company_blueprint.route("/company/<int:id>", methods=["GET", "POST"])
@login_required
def company_profile(id):
    company: Company = Company.query.get(id)
    form = CompanyForm()
    if form.validate_on_submit():
        company.title = form.title.data,
        company.location = form.location.data,
        company.save()

        flash("Company has been successfully updated", "info")
        return redirect(url_for("company.companies"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    elif request.method == "GET":
        form.title.data = company.title
        form.location.data = company.location
    return render_template("company/company_creation_profile.html", form=form, company_id=company.id)


@company_blueprint.route("/company/creation", methods=["GET", "POST"])
@login_required
def company_creation():
    form = CompanyCreationForm()
    if form.validate_on_submit():
        company = Company(
            title=form.title.data,
            location=form.location.data,
        )
        company.save()
        flash("Creation successful. The new company is created.", "success")
        return redirect(url_for("company.companies"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    return render_template("company/company_creation_profile.html", form=form)


@company_blueprint.route("/company/deletion/<int:id>")
@login_required
def company_deletion(id):
    company: Company = Company.query.get(id)
    company.delete()
    return redirect(url_for('company.companies'))

app/views/employee.py
from flask import render_template, Blueprint, flash, request, redirect, url_for
from flask_login import login_required
from app.forms import AddEmployeeForm, EmployeeForm
from app.models import Employee, Company

employee_blueprint = Blueprint("employee", __name__)


@employee_blueprint.route("/employees", methods=["GET"])
@login_required
def employees():
    employees = Employee.query.all()
    return render_template("employee/employees.html", employees=employees)

@employee_blueprint.route("/employee/creation", methods=["GET", "POST"])
@login_required
def employee_creation():
    form = AddEmployeeForm()
    if form.validate_on_submit():
        employee = Employee(
            name=form.name.data,
            position=form.position.data,
            phone=form.phone.data,
            email=form.email.data,
            birthday=form.birthday.data,
            company_id=int(form.company_id.data.id),
        )
        employee.save()
        flash("Employee has been successfully added", "info")
        return redirect(url_for("employee.employees"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    return render_template("employee/employee_creation_profile.html", form=form)

@employee_blueprint.route("/employee/deletion/<int:id>")
@login_required
def employee_deletion(id):
    employee_to_delete: Employee = Employee.query.get(id)
    employee_to_delete.delete()
    return redirect(url_for("employee.employees"))

@employee_blueprint.route("/employee/<int:id>", methods=["GET", "POST"])
@login_required
def employee_profile(id):
    employee: Employee = Employee.query.get(id)
    form = EmployeeForm()
    if form.validate_on_submit():
        employee.name = (form.name.data,)
        employee.position = (form.position.data,)
        employee.phone = (form.phone.data,)
        employee.email = (form.email.data,)
        employee.birthday = (form.birthday.data,)
        employee.company = (form.company_id.data,)
        employee.save()
        flash("Employee successfully updated", "info")
        return redirect(url_for("employee.employees"))
    elif form.is_submitted():
        flash("The given data was invalid.", "danger")
    elif request.method == "GET":
        form.name.data = employee.name
        form.position.data = employee.position
        form.phone.data = employee.phone
        form.email.data = employee.email
        form.birthday.data = employee.birthday
        form.company_id.data = Company.query.filter_by(id=employee.company_id).first()
    return render_template("employee/employee_creation_profile.html", employee_id=employee.id, form=form)

@employee_blueprint.route("/company/<int:id>/employees", methods=["GET", "POST"])
@login_required
def company_employees(id):
    company_employees = Employee.query.filter_by(company_id=id)
    company = Company.query.get(id)
    return render_template("employee/employees.html", employees=company_employees, company=company)

app/templates/company/companies.html
{% extends "base.html" %}

{% block content %}
<div class="container">
    <h1 class="text-center">Companies</h1>
    <hr>
    {% if companies %}
    <div class="row d-flex justify-content-between">
        {% for company in companies %}
            <div class="card m-3 col-md-5 col-lg-4">
                <div class="card-body">
                    <h4 class="card-title">{{ company.title }}</h4>
                    <p class="card-text">{{ company.location }}</p>
                    <div class="d-flex justify-content-between">
                        <a href="{{ url_for('company.company_profile', id=company.id) }}" class="card-link">Profile</a>
                        <a href="{{ url_for('employee.company_employees', id=company.id) }}" class="card-link">Employees</a>
                        <a href="{{ url_for('company.company_deletion', id=company.id) }}" class="card-link">Delete</a>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    {% else %}
        <p class="text-center pt-100 text-muted">There is no companies yet.</p>
    {% endif %}
    <hr>
    <div class="d-flex flex-column text-center">
        <p class="text-secondary">Want to create a company? Press the button below.</p>
        <a class="btn btn-primary" href="{{ url_for('company.company_creation') }}" role="button">Create Company</a>
    </div>

</div>
{% endblock %}

app/templates/company/company_creation_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
  <div class="card w-50 mx-auto">
    <div class="card-header">
      <h4 class="card-title">Company{% if not company_id %} Creation{%endif%}</h4>
    </div>
    <div class="card-body">
      <form class="form" role="form" {% if company_id %} action="{{ url_for('company.company_profile', id=company_id) }}" {% else %} action="{{ url_for('company.company_creation') }}" {% endif %} method="post">
        <div class="form-group">
          {{form.title.label}}
          {{form.title(class='form-control')}}
          {% for error in form.errors.title %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>
        <div class="form-group">
          {{form.location.label}}
          {{form.location(class='form-control')}}
          {% for error in form.errors.location %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>

        {{form.submit(class='btn btn-primary')}}
      </form>
    </div>
  </div>
</div>
{% endblock %}

app/templates/company/company_profile.html
{% extends 'base.html' %}

{% block content %}
<div class="container py-4">
  <div class="card w-50 mx-auto">
    <div class="card-header">
      <h4 class="card-title">Company</h4>
    </div>
    <div class="card-body">
      <form class="form" role="form" action="{{ url_for('company.company_profile', id=company_id) }}" method="post">
        {{ form.hidden_tag() }}
        <div class="form-group">
          {{form.title.label}}
          {{form.title(class='form-control')}}
          {% for error in form.errors.title %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>
        <div class="form-group">
          {{form.location.label}}
          {{form.location(class='form-control')}}
          {% for error in form.errors.location %}
            <small class="text-danger">{{error}}</small>
          {% endfor %}
        </div>
        {{form.submit(class='btn btn-primary')}}
      </form>
    </div>
  </div>
</div>
{% endblock %}